### PR TITLE
Apply style to social media links

### LINKED ISSUE #903: Add hover/click states for social links on the People cards
People cards are currently displayed on the following pages:

- https://okfn.org/who-we-are/our-team/
- https://okfn.org/who-we-are/our-board/
- Network members pages, such as https://okfn.org/network/greece/

The links to social profiles should follow the same styles used in texts: 

- links are coloured with #00A9E0
- on hover - changes color to #E077FF
- on click - changes color to #000000

### PR DESCRIPTION
**Pull request by shashigharti**
- Fixes #903

### CODE REVIEW

**Comment by pdelboca** [comment]
@lucpretti this PR changes the style of the links to look like these:

image

Is this the desired outcome?

**Comment by lucpretti** [comment]
Thank you @pdelboca.

Please add the `@` before the Twitter handle. Then we're good to merge.

**Comment by pdelboca** [comment]
@lucpretti there is a discrepancy on how X data is handled.

Some X accounts are `@username` and others are `username`. We should uniform this. 

My opinion is that in our database we should store `username` and then manage the `@` in the frontend since the X URL is not `x.com/@username` but rather `x.com/username` (although `x.com/@username` will not raise an error it will redirect to `x.com/username`)

**Comment by lucpretti** [comment]
Agree to normalise our database to `username` and manage the `@` in the frontend. Is there a way to do it in a batch?

**Comment by pdelboca** [comment]
Okay! I'll update to handle it in the frontend.

Yeah, but it would be more costly than actually doing it by hand. We need to edit just a few of them. 😄

**Comment by lucpretti** [comment]
No problem! I'll do it by hand then!

**Review by pdelboca — APPROVED** [review]

**Pull request merged**
