### PR TITLE
Add footer plugin

### LINKED ISSUE #900: Make the footer editable
The footer is currently hardcoded. I want to be able to edit it.

The most urgent changes are:

- [ ] update the link on `Request a quote` to https://okfn.org/contacts
- [ ] Add a link to OKFN's Mastodon account in the third column: https://fosstodon.org/@okfn

### PR DESCRIPTION
**Pull request by shashigharti**
- fixes #900
- Added footer plugin using static placeholder so that it is common for all the pages. If the footer is not added, it will use the default html code from _footer.html.

### CODE REVIEW

**Comment by pdelboca** [comment]
@shashigharti I'm a little bit skeptic about this one since I think it would be difficult for @lucpretti to get a similar and consistent look:
- There is no way to edit the background color.
- The layout will be difficult to replicate with plugins.
- I can't imagine a way to replicate our current footer with this.

@lucpretti I think this one could use a little bit of extra work in the requirements. 
 - What are you specifically looking to edit and how? 
 - Is a blank canvas where you can play around with current plugins good for what you need?
 - Do you want to edit the layout of the footer?
 - Just the links?
 - What if we provide a fixed layout and style for you to just edit links and text?

**Comment by shashigharti** [comment]
@pdelboca Thank you for the review!. I was thinking like this - allowing to add footer html. What do you think of it?
footer



[footer.txt](https://github.com/okfn/website/files/12461775/footer.txt)

**Comment by pdelboca** [comment]
@shashigharti I'm usually against rendering user input since it is a source of attacks and vulnerabilities. So I wouldn't go to that approach. Also, if we modify a class or something then we need to manually update this content.

In my opinion there are several possible options ordered by what I think would be the effort:
 - Keep it as now in production and **not make it editable**. Thinking on the tradeoff of time consumed for development vs frequency of update. If the footer is updated once every 6 months by changing just a link maybe it's just easier and cheaper to ask for it to a developer.
 - The option as is in this PR, will give @lucpretti the possibility to edit the footer as we would add a footer to an email. Exact same situation, exact same UX. Maybe it's simple and enough. It will be difficult to mimic the current layout but maybe he can create a new one. It will require though to change the background to blue.
 - Code a fix grid in a footer block to mimic the current production layout and then allow @lucpretti to edit it's blocks. (By adding 1 plugin for each content: `FooterImage`, `FooterLinks`, `FooterText`)
 - Re-design the footer into a more flex layout direction column and create new plugins that can be added on top of each  other. (but this will require a redesign of the footer and I think it is going to be more work.)

**Comment by shashigharti** [comment]
Thanks! Yes agree with all options and I would go for option 1 as footer is not changed frequently. I will wait for the feedback from @lucas.

**Comment by lucpretti** [comment]
@pdelboca @shashigharti I agree with you - better and cheaper to do minor updates to the footer with the help of a developer as it won't get updated often. 

Here's the issue with the immediate changes needed: #984

**Comment by shashigharti** [comment]
Closing this PR and submitting new one.

**Pull request closed without merging**
