### PR TITLE
replace el-salvador flag file with correct flag.

### LINKED ISSUE #374: The El Salvador flag on the network page is not the flag of El Salvador

### PR DESCRIPTION
**Pull request by yotammanor**
fix #374.

The replaced flag belongs to Eritrea. Replaced the flag with the correct one.

### CODE REVIEW

**Comment by yotammanor** [comment]
@brew note that I'm not on slack at the moment, so contact me here if needed :)

**Comment by yotammanor** [comment]
@morchickit this is the fix for #374.

**Comment by yotammanor** [comment]
@pwalsh be aware that this PR needs to be merged and deployed.

**Comment by pwalsh** [comment]
@yotammanor do you not have permissions for that?

**Comment by yotammanor** [comment]
@pwalsh I got an email today that I got removed from okfn on github. With this removal, my merging permissions went away as well. I can pull and deploy, I think.

**Comment by pwalsh** [comment]
@yotammanor it would be really handy if you did not remove yourself from our slack :)

**Comment by yotammanor** [comment]
@pwalsh I was always one such message away :)

**Pull request merged**
