### PR TITLE
2019 update

### PR DESCRIPTION
**Pull request by smth**

### CODE REVIEW

**Comment by roll** [comment]
@smth 
@StephenAbbott 
It seems to have been deployed (I think I've already mentioned that this site is so complicated that it's hard to say definitely =) ). I don't see the video though

https://next.okfn.org/

**Comment by smth** [comment]
Yup, looks like it has been (video needs to be added via the CMS).

**Comment by roll** [comment]
Thanks @smth

**Comment by StephenAbbott** [comment]
Thanks @roll and @smth!

Spotted the video slot appearing on next.okfn.org when I looked earlier. Will do the necessary edits via the CMS now.

**Pull request merged**
