### PR TITLE
Add plugins for list and stats

### LINKED ISSUE #895: Create additional plugins for lists and stats
To be added to the group OKF v2:
---

- [ ] Content List (search for "list" [here](https://ishigami.github.io/okfn_front/components-2.html))
Obs: Instead of a new plugin, could be a new variation to the `Article Link` (#892)

Screenshot 2023-07-10 at 12 05 35

---

- [ ] Number stats (search for "number" [here](https://ishigami.github.io/okfn_front/components-2.html))
    - [ ] Grid 1
    - [ ] Grid 2
    - [ ] Grid 3
Obs: Instead of a new plugin, could be new variations to the `Feature Block`

Screenshot 2023-07-10 at 12 08 05

---

### PR DESCRIPTION
**Pull request by shashigharti**
- fixes #895
- Add content list and number stat plugin

### CODE REVIEW

**Comment by pdelboca** [comment]
@shashigharti looks good! I'm not a fan of the duplication of templates but it looks like necessary. Can we avoid duplicated templates using `justify-content: space-around;` property? Flexbox should be able to align 2,3,4...n easily.

@lucpretti what's the goal of  having `Grid 1` `Grid 2` and `Grid 3` as separated instead of just `Single` and `Multiple`? Maybe I'm being too picky here but these kind of design patterns, if flourish in the site, can lead to a lot of duplicated code and I don't see major differences on how we display 2 or 3 (or 4, 5, etc).

**Comment by pdelboca** [comment]
@shashigharti @lucpretti "Content List" is now a Plugin and a Placeholder. That will create confusion in the future. Can we rename them? 

`Content List` placeholder is only to list `Content List` elements? What's the idea?

**Comment by lucpretti** [comment]
> @shashigharti looks good! I'm not a fan of the duplication of templates but it looks like necessary. Can we avoid duplicated templates using `justify-content: space-around;` property? Flexbox should be able to align 2,3,4...n easily.
> 
> @lucpretti what's the goal of having `Grid 1` `Grid 2` and `Grid 3` as separated instead of just `Single` and `Multiple`? Maybe I'm being too picky here but these kind of design patterns, if flourish in the site, can lead to a lot of duplicated code and I don't see major differences on how we display 2 or 3 (or 4, 5, etc).

It's totally ok to make it multiple instead of the specific numbers.

**Comment by lucpretti** [comment]
> @shashigharti @lucpretti "Content List" is now a Plugin and a Placeholder. That will create confusion in the future. Can we rename them?
> 
> `Content List` placeholder is only to list `Content List` elements? What's the idea?

Let's change the name to `Content Headlines`.

**Comment by shashigharti** [comment]
Thank you! @pdelboca @lucpretti . I will revise the code .

**Comment by shashigharti** [comment]
@pdelboca I have made the changes and it is ready for review!. 
1. Content list => Content Headlines.
2. Number stat => Number Stats Block.
3. Changed number stat types to 'single' and 'multiple'.
4. Use same template for multiple stats.

**Comment by pdelboca** [comment]
@shashigharti looks good!

I think there is a small issue with how we display multiple singles. If you add two elements to a single layout it should be displayed one in top of another right?

image

**Comment by pdelboca** [comment]
@shashigharti thanks!

One last thing: The arrow icon next to the `Learn more` link is not being shown. (See UI designs)

**Comment by shashigharti** [comment]
Thank you @pdelboca!. It is fixed.
fixed

**Comment by pdelboca** [comment]
Thanks @shashigharti !

**Review by pdelboca — APPROVED** [review]

**Pull request merged**
