### PR TITLE
handle short text on home page

### PR DESCRIPTION
**Pull request by smth**

### CODE REVIEW

**Comment by roll** [comment]
@smth 
I've deployed the update

Could you please try if updating works now - https://next.okfn.org/tools-services/?edit

**Comment by smth** [comment]
I'm not seeing the CSS change. Deleting still hangs for me.

**Comment by roll** [comment]
@smth 
Ahh yea, sorry, I also need to do this on every deploy - https://github.com/okfn/website#static-files (and it's kinda slow). Is the CSS in-place now?

Just to clarify what exact block you're trying to delete (Data wrangling and analysis?)? I'm going to test it I though it was regarding editing

**Comment by smth** [comment]
Yup, CSS updated now.

Yeah, that is one of the items I was trying to delete.

**Comment by roll** [comment]
@smth 
I've disabled something called `PressMention`. It was mentioned in this admin error and I didn't find where this entity was used on the site.

Deploying now, locally I was able to delete blocks.

**Comment by roll** [comment]
It's deployed. Works fine for me now

**Comment by smth** [comment]
Weird, still hanging for me.

**Comment by roll** [comment]
Could you please collect some info about it? Console errors in the browser (chrome?) and maybe some other hints? BTW does it work locally?

**Comment by smth** [comment]
OK, looks like it either works in Chromium, but not Firefox, or just not working in the browser I was using previously (Firefox). This is in regards to staging; it has always worked locally.

Not sure if this is an error, but in Firefox:
```
Content Security Policy: The page’s settings observed the loading of a resource at https://next.okfn.org/admin/cms/page/delete-plugin/7966/ (“default-src”). A CSP report is being sent.
```

**Comment by roll** [comment]
Thanks! I saw this warning in the chrome console also. I'll create an issue for it

**Comment by roll** [comment]
https://github.com/okfn/website/issues/427

**Pull request merged**
