### PR TITLE
Change Open Knowledge International to Open Knowledge Foundation

### PR DESCRIPTION
**Pull request by StephenAbbott**

### CODE REVIEW

**Comment by roll** [comment]
@StephenAbbott 
I guess this one is not actual now and we can close?

**Comment by StephenAbbott** [comment]
@roll It is still current/actual now. Alt text for all images on okfn.org still use OKI rather than OKF

**Comment by roll** [comment]
@StephenAbbott 
I mean on master which is not deployed yet we already have:
```
foundation/press/templates/press/pressresources.html
17:        <img src="//a.okfn.org/img/oki/standard-rgb-667x687.png" alt="Open Knowledge Foundation">
42:        <img src="//a.okfn.org/img/oki/standard-grey-667x687.png" alt="Open Knowledge Foundation">
67:        <img src="//a.okfn.org/img/oki/standard-white-667x687.png" alt="Open Knowledge Foundation">
101:        <img src="//a.okfn.org/img/oki/landscape-rgb-936x244.png" alt="Open Knowledge Foundation">
129:        <img src="//a.okfn.org/img/oki/landscape-grey-936x244.png" alt="Open Knowledge Foundation">
157:        <img src="//a.okfn.org/img/oki/landscape-white-936x244.png" alt="Open Knowledge Foundation">
194:        <img src="//a.okfn.org/img/oki/small-rgb-433x344.png" alt="Open Knowledge Foundation">
219:        <img src="//a.okfn.org/img/oki/small-grey-432x344.png" alt="Open Knowledge Foundation">
244:        <img src="//a.okfn.org/img/oki/small-white-433x344.png" alt="Open Knowledge Foundation">
```

**Comment by roll** [comment]
I guess this updated was applied in the Sam's work

**Comment by StephenAbbott** [comment]
Ah OK. Sorry

**Pull request closed without merging**
